spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://121.136.10.35:63333/user_info?characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username : adminA
    password : P@ssw0rd

  jpa :
    hibernate:
      ddl-auto : none
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org:hibernate:SQL: DEBUG