spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/user_info?characterEncoding=utf8&autoReconnect=true
    username : root
    password : sksms331

  jpa :
    hibernate:
      ddl-auto : none
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org:hibernate:SQL: DEBUG